### ISSUE TITLE
Schedules in github actions are disabled in forks by default

### ISSUE THREAD

**Issue by aubelsb2** [1set/cronrange#16]
Scheduled github actions are diabled in forks on github by default. I believe that is correct as I don't want to enable it as it might mean that I get notifications every day about a build failure. 

![image](https://user-images.githubusercontent.com/20219956/128655523-3904ea49-2875-4f5e-952d-17285e43611d.png)

However as a result I don't get automated tests upon pushing it. Perhaps split the github action into 2:
Scheduled: for integration components
Test: For running on push and on pull request go test, coverage and lint actions?

**Comment by vt128** [comment]
> Require approval for first-time contributors who are new to GitHub
> Only first-time contributors who recently created a GitHub account will require approval to run workflows.

Adjusted to this policy.
